name: Report Bug 🪲
description: Create a bug report
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Please provide as many details as possible to help us evaluate and resolve the bug report quickly.

  - type: markdown
    attributes:
      value: |
        Software-specific details:

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Name and version of the operating system you're using.
      placeholder: e.g., Windows 11, macOS 14.1, Ubuntu 22.04
    validations:
      required: true

  - type: textarea
    id: bug
    attributes:
      label: Bug Description
      description: Describe what the bug is and how it manifests.
      placeholder: A clear description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps needed to reproduce this behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: A clear description of what you expected to happen.
    validations:
      required: true

  - type: input
    id: hash
    attributes:
      label: Commit Hash
      description: The commit hash where you encountered this issue (if known).
      placeholder: e.g., baf2aab0128f07262b564214ec70fc07befc6bb3

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, logs, or screenshots about the bug.
