name: Feature Request 🔮
description: Suggest an idea for this project
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Please provide details about your feature request. The development team will review and consider your suggestion.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does your feature request aim to solve? Please describe it.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe your proposed solution in detail.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: What alternative solutions have you considered?

  - type: textarea
    id: implementation
    attributes:
      label: Implementation
      description: Provide a code example of how this feature could be implemented.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples here.
